spring.application.name=image-dispatch-service

# ===============================
# DATASOURCE - POSTGRES
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/image_dispatch
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
[

# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# AWS SDK
# ===============================
aws.s3.bucket=image-dispatch-bucket
aws.region=us-east-1

# ===============================
# SMTP
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mclaracontact@gmail.com
spring.mail.password=qsjbiwpcgfhkoeea
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
